runtime: python312
instance_class: F1
entrypoint: gunicorn -b :$PORT app:app

automatic_scaling:
  max_instances: 2
  target_cpu_utilization: 0.65
  min_instances: 0

handlers:
  - url: /.*
    script: auto
    secure: always
